### ISSUE TITLE
How are the signs of the ideal point determined?

### ISSUE THREAD

**Issue by pqnelson** [kosukeimai/emIRT#2]
I've been working through the example code given in the R-documentation, specifically:

``` R
## Data from 109th US Senate
data(s109)

## Convert data and make starts/priors for estimation
rc <- convertRC(s109)
p <- makePriors(rc$n, rc$m, 1)
s <- getStarts(rc$n, rc$m, 1)

## Conduct estimates
lout <- binIRT(.rc = rc,
               .starts = s,
               .priors = p,
               .control = {
                   list(threads = 1,
                        verbose = FALSE,
                        thresh = 1e-6
                       )
               }
               )

## Look at first 10 ideal point estimates
lout$means$x[1:10]
```

How does `binIRT` determine the _sign_ of the ideal points? (In this case, positive numbers appear to correspond to indicate the magnitude of "conservative-ness", and negative numbers to "liberal-ness" --- will this be the case in general? Or is the first legislator in the `rc` always positive?)

**Comment by olmjo** [comment]
@pqnelson, the code you've pasted there has the orientation/polarity implicitly determined by the starting values and the priors. With different starting values, but everything else the same, you could end up with a flipped orientation.

In the following two calls, the orientation of the spectrum is determined explicitly. For `lout2`, the scale is oriented so that Sen. Sessions (more conservative than average) has "more" of the latent trait (in this case, conservative ideology). For `lout3`, the scale is oriented so that Sen. Boxer (more liberal than average) has "more" of the latent trait (in this case, liberal ideology). The values passed to `.anchor_subject` correspond to their order: Sen. Sessions' votes are in the 2nd row and Sen Boxer's votes are in the 10th row.

```
lout2 <- binIRT(.rc = rc,
                .starts = s,
                .priors = p,
                .control = {
                    list(threads = 1,
                         verbose = FALSE,
                         thresh = 1e-6
                         )
                },
                .anchor_subject = 2
                )
                                        # Rotates so that Sen. Sessions (R AL)
                                        # has more of the estimated trait
lout3 <- binIRT(.rc = rc,
                .starts = s,
                .priors = p,
                .control = {
                    list(threads = 1,
                         verbose = FALSE,
                         thresh = 1e-6
                         )
                },
                .anchor_subject = 10
                )
                                        # Rotates so that Sen. Boxer (D CA)
                                        # has more of the estimated trait
```

In the US legislative setting, it's usually straightforward enough to identify a good anchor for the spectrum, but in your application it may differ.

**Comment by olmjo** [comment]
@pqnelson , I'm going to close this, but please reach back out if you have any other questions on this. Thanks!
